<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/jquery-2.1.0.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/bootstrap.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/angular.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/angular-resource.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/angular-route.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/angular-animate.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/angular-sanitize.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/ui-bootstrap-tpls-0.11.0.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/textAngular.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/textAngular-sanitize.min.js"></script>
<script
	src="${pageContext.request.contextPath}/resources/vendor/scripts/textAngular-rangy.min.js"></script>
